version: "3.8"
services:
  backend:
    build: ./suems
    container_name: suems-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/suems
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: suems-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: suems
    restart: always
    environment:
      MYSQL_DATABASE: suems
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - suems_data:/var/lib/mysql

volumes:
  suems_data:
