services:
  # Frontend Service (Nginx)
  - type: web
    name: suems-frontend
    env: docker
    rootDir: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    domains:
      - suems.onrender.com
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /

  # Backend Service (Spring Boot)
  - type: web
    name: suems-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        value: your_database_url
      - key: DB_USERNAME
        value: your_database_username
      - key: DB_PASSWORD
        value: your_database_password
    autoDeploy: true
    domains:
      - suems-api.onrender.com
