spring.application.name=suems

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/suems
spring.datasource.username=root
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true


# -----------------------------------------------
# 🔹 SIMULATOR CONFIG (for mock energy data)
# -----------------------------------------------
suems.simulator.enabled=true
suems.simulator.interval-ms=10000